---
- name: install php packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - php5-fpm
    - php5-intl
    - php5-common
    - php5-curl
    - php5-dev
    - php5-xdebug
    - php5-mysql
  notify: restart php-fpm